name: log-streamer

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      #      - mongo_db_data:/data/db
      - ../../migrations/mongo:/docker-entrypoint-initdb.d

#volumes:
#  mongo_db_data: